In [15]:
import os
import glob
import pandas as pd

%cd "C:\\Users\\kato\\OneDrive\\ドキュメント\\B2\\graduation research"

folder_path ="kasyo"

# フォルダ内の“kasyo”を含むファイル名を取得する
kasyo_files = glob.glob(os.path.join(folder_path, '*kasyo01*'))

kasyo_data = []
# 結果を表示します
for file in kasyo_files:
    dic_file = [file]
    print(file)
    kasyo_data = kasyo_data + dic_file
    
# 'kasyo_data'をpythonで読み込めるデータフレームにする
df = pd.read_excel(kasyo_data[0])
from IPython.display import display

header_list = df.columns.tolist()
list_length = len(header_list)
print(list_length)

col = 0
while col <= list_length - 1 :
    header_list[col]=col
    col=col+1

print(header_list)

df.columns = header_list

df = pd.DataFrame(df)
display(df)

C:\Users\kato\OneDrive\ドキュメント\B2\graduation research
kasyo\kasyo01.xlsx
159
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158]

,0,1,2,3,4,5,6,7,8,9,...,149,150,151,152,153,154,155,156,157,158
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,北海道,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,国土交通省道路局
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,基本区間番号\n交通調査●●,世代管理番号,NaN,道 路 種 別,路 線 名,NaN,起 点 側,NaN,NaN,NaN,...,運用の有無\nリバーシブルレーン,アクセスコントロール,平成27年度,NaN,基本区間番号\n交通調査●●,世代管理番号,NaN,道 路 種 別,路 線 名,NaN
4,NaN,NaN,NaN,NaN,路 線 番 号,路 線 名,接 続 区 分,接続路線等,NaN,NaN,...,NaN,NaN,指定市コード\n都道府県●●,単位区間番号\n道路状況調査,NaN,NaN,NaN,NaN,路 線 番 号,路 線 名
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,01796240020,0,0,7,624,札幌東部新道２号線,1,01110500324,0,道央自動車道,...,2,4,1100,80190,01796240020,0,0,7,624,札幌東部新道２号線
4887,01796240030,0,1,7,624,札幌東部新道２号線,1,01611380027,0,厚別平岡線,...,2,4,1100,80190,01796240030,0,1,7,624,札幌東部新道２号線
4888,01708260010,0,0,7,826,川沿石山連絡線,1,01302300100,0,一般国道２３０号,...,2,4,1100,80130,01708260010,0,0,7,826,川沿石山連絡線
4889,01708260020,0,0,7,826,川沿石山連絡線,1,01304530045,0,一般国道４５３号,...,2,4,1100,80140,01708260020,0,0,7,826,川沿石山連絡線
4890,01709770010,0,0,7,977,菊水元町６条中通１号線,1,01302740100,0,一般国道２７４号,...,2,4,1100,80150,01709770010,0,0,7,977,菊水元町６条中通１号線

In [17]:
col1 = 75
col2 = 140

In [ ]:
# いらない(データが空白だったり、文字列だったりする)行を削除する
rows = df.shape[0]     # データが何行あるか(作業する幅)を'rows'として保存
del_rows = []          # 消したい行がどんどんぶち込まれていく空のゴミ箱(リスト)
now_row = 0            # 0行目からローラーしていく作戦

# 欠損値及び文字列を含む行を抽出（今欠損地があって困るのは75列目と140列目なので、75列目と140列目の0行目から順に欠損していないか確認していく）
while now_row < rows:
    cel1 = df.iloc[now_row, col1]        # 75列目、'now_row'行目のセルを'cel1'としてみる。
    cel2 = df.iloc[now_row, col2]       # 140列目、'now_row'行目のセルを'cel2'としてみる。

    # 'cel1'もしくは'cel2'が欠損値だった場合、その行をゴミ箱にぶち込む
    if True == pd.isna(cel1) or True == pd.isna(cel2):
        del_rows = del_rows + [now_row]
    # 'cel1'もしくは'cel2'が文字列だった場合もその行をゴミ箱にぶち込む
    elif isinstance(cel1,(str)) or isinstance(cel2,(str)):
        del_rows = del_rows + [now_row]
    # それ以外だった場合(基本的には数値しか残らない)、とりあえずやることなし
    else:
        pass
# 分岐してそれぞれの作業が終わったら、次の行へ移動
now_row = now_row+1


# 数値以外のcellを含む行を削除する（先ほどゴミ箱にぶち込んだ行を完全に削除する）
df_new = df.drop(del_rows)
df_new = df_new.reset_index(drop = True)    # 行のヘッダーがめちゃくちゃになったので整理

display(df_new)

In [4]:
# 不要な列を削除する
del_list = header_list[6:]
print(del_list)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158]

In [7]:
keep_cols = [75]
df_new = df.loc[:, list(df.columns[:6]) + keep_cols]
display(df_new)

                  0       1    2              3        4            5     75
0                NaN     NaN  NaN            NaN      NaN          NaN   NaN
1                北海道     NaN  NaN            NaN      NaN          NaN   NaN
2                NaN     NaN  NaN            NaN      NaN          NaN   NaN
3     基本区間番号\n交通調査●●  世代管理番号  NaN  道　路　種　別　　　　　　    路　線　名          NaN   NaN
4                NaN     NaN  NaN            NaN  路　線　番　号        路　線　名   NaN
...              ...     ...  ...            ...      ...          ...   ...
4886     01796240020       0    0              7      624    札幌東部新道２号線  57.4
4887     01796240030       0    1              7      624    札幌東部新道２号線  40.9
4888     01708260010       0    0              7      826      川沿石山連絡線  29.3
4889     01708260020       0    0              7      826      川沿石山連絡線  24.7
4890     01709770010       0    0              7      977  菊水元町６条中通１号線  23.2

[4891 rows x 7 columns]

In [9]:
output_file_path = r"\new_data\kasyo01.xlsx"

result_column = df.iloc[8:, 75] - df.iloc[8:, 140]

# 結果をデータフレームに追加
df_new['Result'] = result_column
df_new = pd.DataFrame(df_new)
display(df_new)

,0,1,2,3,4,5,75,Result
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,北海道,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,基本区間番号\n交通調査●●,世代管理番号,NaN,道 路 種 別,路 線 名,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,路 線 番 号,路 線 名,NaN,NaN
...,...,...,...,...,...,...,...,...
4886,01796240020,0,0,7,624,札幌東部新道２号線,57.4,-2.6
4887,01796240030,0,1,7,624,札幌東部新道２号線,40.9,-19.1
4888,01708260010,0,0,7,826,川沿石山連絡線,29.3,-20.7
4889,01708260020,0,0,7,826,川沿石山連絡線,24.7,-25.3
4890,01709770010,0,0,7,977,菊水元町６条中通１号線,23.2,-26.8